name: Deployment

on:
  push:
    branches:
      - ci

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: ssh into EC2 and execute commands
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DROPLET_HOST }}
          username: ${{ secrets.DROPLET_USER }}
          key: ${{ secrets.DROPLET_SSH_KEY }}
          script: |
            export PATH=$HOME/n/bin:$PATH
            export PATH=$HOME/.local/share/pnpm:$PATH
            cd animechan
            ./deploy.sh
