name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: actions

    strategy:
      matrix:
        node-version: [18.x, 19.x, 20.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Run the tests
        run: pnpm test
